<<<<<<< HEAD
function [population,it] = myGA(f,V,M,lb,ub)
=======
function [population,it] = myGA(f,V,M,lb,ub,N,NP,NC,P,eta)

>>>>>>> 653137422dc487acfcc82e3ca24f852d1fccc55e
	% myGA(f,V,M,lb,ub)
	% f : function to minimize
	% V : Dimension of the search space.
	% M : Number of objectives.
	% lb = lower bound vector.
	% ub = upper bound vector. 

	%% DEFINITION OF THE PARAMETERS

<<<<<<< HEAD
	N = 60;    % Population size
	NP = 25;    % Size of the mating pool 
	NC = 25;    % Number of children generated by generation
	P = 0.3;     % probability of recombination

    diffarea=[];

=======
	N = 50;    % Population size
	NP = 25;    % Size of the mating pool 
	NC = 25;    % Number of children generated by generation
	P = 0.4;     % probability of recombination
>>>>>>> 653137422dc487acfcc82e3ca24f852d1fccc55e
	verbose = true; % (true) plots each iteration
    q = [];
    gem = [];
    crowdis = [];
<<<<<<< HEAD
    qnew=10;
=======
>>>>>>> 653137422dc487acfcc82e3ca24f852d1fccc55e
	%% GENETIC ALGORITHM

	% Generation of the intial population
	population = initPopulation(N,V); % [10 *2] 

	population = evaluatePopulation(population,f,N,V,M,lb,ub); %10*3

<<<<<<< HEAD
	population = sortPopulation(population,V,M,qnew);
=======
	population = sortPopulation(population,V,M);
>>>>>>> 653137422dc487acfcc82e3ca24f852d1fccc55e

	% Main loop
	
%%%%%%%%%%%%%%%%%%%%%%%% \\ Do not change this part of the code!!
	it = 1;
	runFlag = true;
	while runFlag
%%%%%%%%%%%%%%%%%%%%%%%% \\ Proceed with changes below!
<<<<<<< HEAD

		parents = selectionTournament(population,NP,V,M);	

		offspring = geneticOperators(parents,f,N,NC,P,V,M,lb,ub);

		population = [ population(:,1:V+M) ; offspring(:,1:V+M) ]; % vertical on eachother 

		population = sortPopulation(population,V,M,qnew);
=======
     
		parents = selectionTournament(population,NP,V,M);	
        
        eta = 5;

		offspring = geneticOperators(parents,f,N,NC,P,V,M,lb,ub,eta);

		population = [ population(:,1:V+M) ; offspring(:,1:V+M) ]; % vertical on eachother 

		population = sortPopulation(population,V,M);
>>>>>>> 653137422dc487acfcc82e3ca24f852d1fccc55e

		population = cropPopulation(population,N);

        

		% Visualization
		if verbose
			illustratePopulation(population,V,M,lb,ub,it);
			drawnow;
			pause(0.1);
<<<<<<< HEAD
		end

=======
        end
>>>>>>> 653137422dc487acfcc82e3ca24f852d1fccc55e
		it = it+1;
        %% set first time 
        if it == 2
            fitness = 0;
            for i = 1 : size(population,1)
                for m = 1:M 
                    fitness = fitness + population(i,V+m);
                    max_prev = 0;
                end 
            end 
<<<<<<< HEAD
            A_old = fitness + 15;
        end 
		[runFlag,A,qnew,m,crowd,max_crowd] = stopCriterion(population,V,M,A_old,it,max_prev);

        %q = [q qnew];
        A_old = [A_old A];
        %gem = [gem m];
        %crowdis = [crowdis crowd];
=======
            A_old = abs(fitness) + 15/100*abs(fitness);
        end 
		[runFlag,A,qnew,m,crowd,max_crowd] = stopCriterion(population,V,M,A_old,it,max_prev);

        q = [q qnew];
        A_old = [A_old A];
        gem = [gem m];
        crowdis = [crowdis crowd];
>>>>>>> 653137422dc487acfcc82e3ca24f852d1fccc55e
        max_prev = max_crowd;
    
        
    end
end
